Refactored some db checks that use .exists()
Volentix/venue-server pull request #162
Opened 2018-08-05 22:46 UTC by joemarct

This closes #161. Other commits that attempt to optimize DB queries may be added here.

2018-08-08 16:19 UTC, shawnlauzon requested changes
Seems we should be calling `lower` every time we call `strip`.

2018-08-09 03:49 UTC, joemarct commented on venue/views.py
> +        user__email__iexact=data['email'].strip(),
`user__email__iexact` --> The `__iexact` filter here means case insensitive matching, so I think `.lower()` is redundant.

2018-08-09 03:50 UTC, joemarct commented on venue/views.py
> +        user_check = User.objects.filter(username__iexact=data.get('username').strip())
That's why I changed the query to `username__iexact` for case-insensitive matching, same effect as `.lower()`.

2018-08-09 12:51 UTC, shawnlauzon commented on venue/views.py
> +        user__email__iexact=data['email'].strip(),
Ahhh I didn't realize that. Ok, that sounds like it works then.

2018-08-09 12:51 UTC, shawnlauzon approved these changes

2018-08-09 14:20 UTC, merged