Remove useless data from the table
Volentix/venue-server pull request #170
Opened 2018-08-12 00:50 UTC by alexdashkov

Closes #167.

Keep only last week's data and only one raw per day for a user. 
@joemarct Please feel free to advise me about rewriting with an ORM. I can't find a fast way to keep only the latest raw per day without a query per user.

2018-08-13 14:13 UTC, shawnlauzon requested changes
Code appears good, however I've had a change in heart of how much to delete.

2018-08-13 14:13 UTC, shawnlauzon commented on venue/models.py
> +        Remove lines older than 7 days and duplicates for each day
@alexdashkov I've thought about how much data I'm sure that we are now removing, and don't want to remove entries older than 7 days. Disk space is cheap enough that storing 1 entry per user per day is not a problem. As long as the data storage increases in terms of days and not minutes, we are good.

2018-08-16 00:46 UTC, alexdashkov commented
@shawnlauzon it's fixed.

2018-08-16 13:36 UTC, shawnlauzon approved these changes

2018-08-16 13:42 UTC, merged